version: '3.7'

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
